base:
  project: Stroke-detection
  random_state: 16
  target_col: stroke

data_source:
  source: data\raw\healthcare-dataset-stroke-data.csv
interim_data:
  source: data\interim\cat-stroke-data.csv
split_data:
  train_path: data/processed/train_stroke-data.csv
  test_path: data/processed/test_stroke-data.csv
  test_size: 0.2

estimators:

model_dir: models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib